blank_issues_enabled: false
contact_links:
  - name: "\U0001F527 GitHub Pull Requests"
    url: https://github.com/MemDBai/MemDB/pulls
    about: Contribute code improvements via Pull Requests
  - name: "\U0001F4AC GitHub Discussions"
    url: https://github.com/MemDBai/MemDB/discussions
    about: Participate in our GitHub Discussions to ask questions or share ideas
  - name: "\U0001F3AE Discord Server"
    url: https://discord.gg/8vhbTZgf
    about: Join our Discord Server for real-time community chat
