version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - gosec
    - noctx
    - perfsprint
    - usestdlibvars
  settings:
    gosec:
      excludes:
        - G104
        - G304

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
